/* ═══════════════════════════════════════════════════════════
   首爾行程資料 — 符合 app.js renderSeoulDetail 格式
   從 Script 轉換，包含皮克敏攻略
   ═══════════════════════════════════════════════════════════ */

const SEOUL_DATA = {

  flightInfo: {
    outbound: { depart: '7/15 (三) 01:25', arrive: '7/15 (三) 05:00' },
    inbound:  { depart: '7/20 (一) 22:40', arrive: '7/21 (二) 00:10' },
    warning:  '去程提醒：7/14（二）就要提前抵達機場！凌晨班機建議提早 3 小時到。',
  },

  accommodation: {
    name: 'House 204 · 弘大根據地',
    desc: '弘益大學站步行 3–5 分鐘 · 2023 年新建築 · 有電梯',
    price: 'NT$14,443 / 5晚含稅 · ✅ 免費取消',
    tags: ['🧳 支援當日行李寄放','🛗 12人大電梯','🛏 高級床品','❄️ 房控冷氣','📍 弘大商圈核心'],
  },

  dayData: {

    D1: {
      emoji: '✈️',
      title: 'D1 — 抵達弘大，開吃開逛！',
      subtitle: '凌晨 5:00 仁川落地 → Airbnb 寄行李 → 衝出去',
      area: '📍 弘大 · 延南洞 · 合井',
      pikmin: {
        title: 'D1 皮克敏攻略',
        estimate: '🌿 預估花苗 45+',
        tips: [
          { icon:'🗺', text:'弘大站下車後立刻開 APP，出站就開始收集！地鐵站本身算「交通」花苗' },
          { icon:'🌸', text:'弘大商圈一條街密度超高，OLIVE YOUNG、3CE、SPAO 每間都是「商店」花苗，慢慢走別跑' },
          { icon:'☕', text:"延南洞咖啡廳全部是「咖啡廳」花苗，Cafe Layered、Brady's 走一趟至少收 5-8 個" },
          { icon:'🌿', text:'京義線林蔭道步道算「大自然」花苗，傍晚散步一定要開著！' },
          { icon:'💡', text:'弘大是首爾花苗密度 Top 3 的區域，第一天好好收，晚上結算一定超滿足' },
        ],
      },
      sections: [
        { label:'🍳 早上 — 寄完行李，先填飽肚子', spots:[
          { id:'egg-drop', type:'food', name:'Egg Drop 弘大店',
            tags:[{t:'早餐',c:'food'}],
            why:'韓國最夯早餐！厚蛋三明治外酥內嫩，落地第一口就征服首爾',
            desc:'弘大商圈內步行可達，排隊也值得！',
            links:[{cls:'naver',url:'https://map.naver.com/p/search/Egg%20Drop%20홍대',label:'🗺 Naver Map'}] },
        ]},
        { label:'🛍 上午 — 弘大主商圈掃貨', spots:[
          { id:'hongdae-shop', type:'shop', name:'弘大商圈全攻略',
            tags:[{t:'購物',c:'shop'},{t:'拍照',c:'photo'}],
            why:'韓系服飾＋保養品密度最高商圈，韓牌一條街全包，傍晚越夜越熱鬧',
            desc:'首爾最年輕的購物商圈，各種價位都有，以下是重點店家：',
            shops:[
              {label:'🌸 3CE 旗艦店',url:'https://map.naver.com/p/search/3CE%20홍대'},
              {label:'💊 OLIVE YOUNG 弘大',url:'https://map.naver.com/p/search/올리브영%20홍대'},
              {label:'👕 SPAO 弘大',url:'https://map.naver.com/p/search/SPAO%20홍대'},
              {label:'👟 SHOOPEN',url:'https://map.naver.com/p/search/슈펜%20홍대'},
              {label:'🐱 KAKAO FRIENDS',url:'https://map.naver.com/p/search/카카오프렌즈%20홍대'},
              {label:'🏠 Butter 選物店',url:'https://map.naver.com/p/search/버터%20홍대'},
              {label:'🎨 LMC 韓國潮牌',url:'https://map.naver.com/p/search/LMC%20홍대'},
              {label:'📦 DAISO 7層旗艦',url:'https://map.naver.com/p/search/다이소%20홍대'},
              {label:'💅 個人色彩診斷',url:'https://map.naver.com/p/search/퍼스널컬러%20홍대'},
              {label:'📷 韓系證件照',url:'https://map.naver.com/p/search/증명사진%20홍대'},
            ],
            links:[{cls:'naver',url:'https://map.naver.com/p/search/홍대%20상권',label:'🗺 弘大商圈 Naver'}] },
        ]},
        { label:'☕ 下午 — 延南洞文青散策', spots:[
          { id:'yeonnam', type:'photo', name:'延南洞 + 京義線林蔭道',
            tags:[{t:'拍照',c:'photo'},{t:'咖啡',c:'food'}],
            why:'弘大旁的文青聖地，MZ 世代最愛逛，每個轉角都是打卡點',
            desc:'弘大出發步行約10分鐘，獨立咖啡廳＋設計選物小店。',
            shops:[
              {label:"🧇 Cafe Layered 層次蛋糕",url:'https://map.naver.com/p/search/카페레이어드%20연남동'},
              {label:"🥐 Brady's Coffeebar",url:'https://map.naver.com/p/search/브래디스커피바%20연남동'},
              {label:'🏠 Braun Haus 家居風咖啡館',url:'https://map.naver.com/p/search/브라운하우스%20연남동'},
              {label:'📝 made by 文創選物',url:'https://map.naver.com/p/search/메이드바이%20홍대'},
              {label:'👜 fennec 設計師皮夾',url:'https://map.naver.com/p/search/페넥%20홍대'},
              {label:'🌿 延南洞京義線林道',url:'https://map.naver.com/p/search/연남동%20경의선숲길'},
            ],
            links:[{cls:'naver',url:'https://map.naver.com/p/search/연남동%20경의선숲길',label:'🗺 延南洞 Naver'}] },
        ]},
        { label:'🥩 晚餐', spots:[
          { id:'d1-dinner', type:'food', name:'小豬存錢筒烤肉 弘大',
            tags:[{t:'晚餐',c:'food'}],
            why:'弘大知名度最爆表的排隊烤肉！天然石頭烤網減油，五花肉鮮嫩多汁',
            links:[{cls:'naver',url:'https://map.naver.com/p/search/돼지저금통%20홍대',label:'🗺 Naver Map'}] },
        ]},
      ],
      alts:[
        {id:'alt-d1-1',name:'橋村炸雞 弘大',tag:'備選餐',why:'蜂蜜醬炸雞一上桌就停不下來，韓國炸雞天花板',link:'https://map.naver.com/p/search/교촌치킨%20홍대'},
        {id:'alt-d1-2',name:'百年百歲蔘雞湯',tag:'備選餐',why:'弘大名店蔘雞湯，來首爾暖暖胃補補元氣',link:'https://map.naver.com/p/search/백년옥%20홍대%20삼계탕'},
        {id:'alt-d1-3',name:'望遠市場 宵夜小吃',tag:'備選宵夜',why:'在地人才知道！弘大旁傳統市場，糖餅魚板炒年糕超便宜',link:'https://map.naver.com/p/search/망원시장'},
        {id:'alt-d1-4',name:'弘大街頭表演 + 夜店一條街',tag:'備選體驗',why:'傍晚8-9點後 K-POP 舞團大爆發，越夜越熱鬧！',link:'https://map.naver.com/p/search/홍대%20공연거리'},
      ],
    },

    D2: {
      emoji: '👘',
      title: 'D2 — 韓服景福宮 + 益善洞',
      subtitle: '景福宮韓服體驗 → 北村 → 益善洞 → 廣藏市場',
      area: '📍 鐘路區 · 景福宮 · 益善洞 · 廣藏',
      pikmin: {
        title: 'D2 皮克敏攻略',
        estimate: '🌿 預估花苗 60+（全程最高！）',
        tips: [
          {icon:'🏯',text:'景福宮整個園區是「歷史」花苗，穿韓服進去邊拍照邊收，一個宮殿就能收到 10 個以上'},
          {icon:'🏘',text:'北村韓屋村巷弄超密集，每條巷子都有花苗，記得 17:00 前離開！'},
          {icon:'🍵',text:'三清洞一帶咖啡廳密集，藍瓶咖啡、Fritz 都是「咖啡廳」花苗，走一段路就收一個'},
          {icon:'🥘',text:'廣藏市場是「市場」特殊花苗，首爾限定款！邊吃綠豆煎餅邊收超爽'},
          {icon:'💡',text:'今天是全程最高花苗日！鐘路區歷史景點密度全首爾第一，一整天好好走'},
        ],
      },
      sections:[
        { label:'👘 早上 — 韓服體驗 ⭐ 必提前預約！', spots:[
          { id:'hanbok', type:'exp', name:'西花韓服 × 景福宮',
            tags:[{t:'體驗',c:'exp'},{t:'拍照',c:'photo'},{t:'⭐ 必預約',c:'exp'}],
            why:'穿韓服進景福宮免門票，被拍一百張也不夠，景福宮站4號出口走路2分鐘',
            desc:'包含免費編髮、包包配件，6小時方案最充裕。建議一開門就去搶最漂亮款式。',
            warn:'景福宮週二公休！D2 安排週四 ✅ 完全OK！穿韓服進去免門票（省₩3,000）',
            links:[
              {cls:'kkday',url:'https://www.kkday.com/zh-tw/product/3619',label:'🎫 KKday 預約'},
              {cls:'klook',url:'https://www.klook.com/zh-TW/activity/2227-gyeongbokgung-palace-hanbok-rental',label:'🎫 Klook 預約'},
              {cls:'naver',url:'https://map.naver.com/p/search/서화한복',label:'🗺 Naver Map'},
            ] },
          { id:'gyeongbok', type:'photo', name:'景福宮 + 光化門守衛交接',
            tags:[{t:'拍照',c:'photo'},{t:'文化',c:'exp'}],
            why:'韓劇《鬼怪》孔劉同款場景，穿韓服拍照直接女主角上身',
            desc:'守衛交接儀式每天 11:00 & 13:00，超壯觀，拍照超好用。',
            links:[{cls:'naver',url:'https://map.naver.com/p/search/경복궁',label:'🗺 Naver Map'}] },
          { id:'bukchon', type:'photo', name:'北村韓屋村',
            tags:[{t:'拍照',c:'photo'}],
            why:'保存最完整的韓屋巷弄，穿韓服走進去根本穿越朝鮮時代',
            warn:'每日 17:00 後禁止進入核心巷弄，4點前離開！違者罰款₩100,000',
            links:[{cls:'naver',url:'https://map.naver.com/p/search/북촌한옥마을',label:'🗺 Naver Map'}] },
        ]},
        { label:'☕ 下午 — 韓屋咖啡廳 + 益善洞', spots:[
          { id:'anguk-cafe', type:'food', name:'安國站韓屋咖啡廳巡禮',
            tags:[{t:'咖啡',c:'food'},{t:'拍照',c:'photo'}],
            why:'韓屋改造咖啡廳，喝咖啡配昌德宮景色，文青感破表',
            shops:[
              {label:'🫙 藍瓶咖啡 三清店',url:'https://map.naver.com/p/search/블루보틀%20삼청'},
              {label:'🦭 Fritz Coffee 韓屋海豹店',url:'https://map.naver.com/p/search/프릳츠%20안국'},
              {label:'🌿 Cafe SangGuk 昌德宮景觀',url:'https://map.naver.com/p/search/카페상국%20안국'},
            ] },
          { id:'ikseon', type:'food', name:'益善洞韓屋美食街',
            tags:[{t:'下午茶',c:'food'},{t:'拍照',c:'photo'}],
            why:'韓屋改造各種網美餐廳咖啡廳，IG打卡密度全首爾最高的一條街',
            shops:[
              {label:'🍞 Mil Toast 蒸氣手撕吐司',url:'https://map.naver.com/p/search/밀토스트하우스%20익선동'},
              {label:'🍵 清水堂 抹茶起司蛋糕',url:'https://map.naver.com/p/search/청수당%20익선동'},
              {label:'🌊 小夏鹽田 水車造景',url:'https://map.naver.com/p/search/소하염전%20익선동'},
            ],
            links:[{cls:'naver',url:'https://map.naver.com/p/search/익선동',label:'🗺 益善洞 Naver'}] },
        ]},
        { label:'🥘 晚餐', spots:[
          { id:'gwangjang', type:'food', name:'廣藏市場夜市小吃',
            tags:[{t:'晚餐',c:'food'}],
            why:'首爾最強傳統市場！麻藥飯捲吃了真的會上癮，清空胃再來',
            shops:[
              {label:'🥬 順熙家綠豆煎餅',url:'https://map.naver.com/p/search/순희네%20광장시장'},
              {label:'🍱 母女紫菜包飯',url:'https://map.naver.com/p/search/모녀김밥%20광장시장'},
              {label:'🥩 富村生拌牛肉（米其林）',url:'https://map.naver.com/p/search/부촌육회%20광장시장'},
            ],
            links:[{cls:'naver',url:'https://map.naver.com/p/search/광장시장',label:'🗺 廣藏市場 Naver'}] },
        ]},
      ],
      alts:[
        {id:'alt-d2-1',name:'土俗村蔘雞湯',tag:'備選餐',why:'總統也是粉絲！景福宮旁超人氣蔘雞湯',link:'https://map.naver.com/p/search/토속촌삼계탕'},
        {id:'alt-d2-2',name:'昌德宮秘苑',tag:'備選景點',why:'世界文化遺產！朝鮮王室秘密後花園，需提前官網預約！',link:'https://map.naver.com/p/search/창덕궁%20비원'},
        {id:'alt-d2-3',name:'仁寺洞散策',tag:'備選逛街',why:"傳統文化老街，手工藝品、陶藝、茶館聚集，O'sulloc 抹茶醬必買",link:'https://map.naver.com/p/search/인사동'},
        {id:'alt-d2-4',name:'三清洞麵疙瘩（米其林）',tag:'備選宵夜',why:'米其林推薦！小魚熬湯底，蛤蜊帶鮮味，北村旁超順路',link:'https://map.naver.com/p/search/삼청동%20수제비'},
      ],
    },

    D3: {
      emoji: '✨',
      title: 'D3 — 聖水洞潮流日',
      subtitle: '聖水洞旗艦店 → 建大貨櫃屋 → 漢南洞',
      area: '📍 聖水洞 · 建大 · 漢南洞',
      pikmin: {
        title: 'D3 皮克敏攻略',
        estimate: '🌿 預估花苗 50+',
        tips: [
          {icon:'🏬',text:'聖水洞品牌旗艦店全部是「商店」花苗，Dior、TAMBURINS、LCDC 走一圈就收到飽'},
          {icon:'🌿',text:'首爾林公園是「大自然」花苗，傍晚散步時開著 APP，漢江一帶收益很好'},
          {icon:'📦',text:'建大 Under Stand Avenue 貨櫃市集算「商店街」花苗，整個市集走一圈大概 8-10 個'},
          {icon:'🕶',text:'漢南洞選物店也是「商店」花苗，Gentle Monster 旗艦店特別大，停久一點收更多'},
          {icon:'💡',text:'今天移動距離最長，記得每換一個區域就看一下花苗有沒有更新！'},
        ],
      },
      sections:[
        { label:'☕ 早午餐', spots:[
          { id:'cafe-onion', type:'food', name:'Cafe Onion 聖水店',
            tags:[{t:'早午餐',c:'food'},{t:'拍照',c:'photo'}],
            why:'廢墟工廠改造，磚牆玻璃窗工業感爆棚，聖水洞散策最佳起點',
            desc:'Pandoro 酥皮麵包外酥內蓬，美式咖啡必配。要排隊但值得。',
            links:[{cls:'naver',url:'https://map.naver.com/p/search/카페오니언%20성수',label:'🗺 Naver Map'}] },
        ]},
        { label:'🏬 上午 — 聖水洞品牌旗艦店大逛', spots:[
          { id:'seongsu-shop', type:'shop', name:'聖水洞潮流商圈',
            tags:[{t:'購物',c:'shop'},{t:'拍照',c:'photo'}],
            why:'首爾最潮新區！品牌把旗艦店蓋得比美術館還好看，每間都能拍出片',
            shops:[
              {label:'💙 Dior 概念店（外觀必拍）',url:'https://map.naver.com/p/search/디올%20성수'},
              {label:'🪞 TAMBURINS（Jennie代言）',url:'https://map.naver.com/p/search/탬버린즈%20성수'},
              {label:'🐘 Blue Elephant 旗艦',url:'https://map.naver.com/p/search/블루엘리펀트%20성수'},
              {label:'📐 LCDC Seoul 複合空間',url:'https://map.naver.com/p/search/LCDC%20서울%20성수'},
              {label:'✏️ POINT of VIEW 文具（3層）',url:'https://map.naver.com/p/search/포인트오브뷰%20성수'},
              {label:'💊 OLIVE YOUNG 聖水超大店',url:'https://map.naver.com/p/search/올리브영%20성수'},
              {label:'🍞 自然島鹽麵包 聖水',url:'https://map.naver.com/p/search/자연도소금빵%20성수'},
            ],
            links:[{cls:'naver',url:'https://map.naver.com/p/search/성수동%20상권',label:'🗺 聖水洞 Naver'}] },
        ]},
        { label:'🍖 午餐', spots:[
          { id:'gamjatang', type:'food', name:'傳說中的馬鈴薯排骨湯',
            tags:[{t:'午餐',c:'food'}],
            why:'祖傳三代！白種元老師認證，濃稠到快凝固的豬骨湯，小紅書狂推',
            desc:'24小時營業，豬骨湯配白飯一口接一口停不下來。',
            links:[{cls:'naver',url:'https://map.naver.com/p/search/이대감자탕%20성수',label:'🗺 Naver Map'}] },
        ]},
        { label:'📦 下午 — 建大 + 漢南洞', spots:[
          { id:'understand', type:'photo', name:'建大 Under Stand Avenue',
            tags:[{t:'拍照',c:'photo'},{t:'逛街',c:'shop'}],
            why:'彩色貨櫃堆成的藝術市集，背景超獨特，和聖水同一條地鐵線超順路',
            links:[{cls:'naver',url:'https://map.naver.com/p/search/어반스탠스%20건대',label:'🗺 Naver Map'}] },
          { id:'hannam', type:'shop', name:'漢南洞高端選物 + 咖啡廳',
            tags:[{t:'購物',c:'shop'},{t:'拍照',c:'photo'}],
            why:'首爾最有品味的街區，邊佑錫愛店就在這，高端選物品牌聚集地',
            shops:[
              {label:'👓 Gentle Monster',url:'https://map.naver.com/p/search/젠틀몬스터%20한남'},
              {label:'🍰 NUDAKE 甜點旗艦',url:'https://map.naver.com/p/search/누데이크%20가로수길'},
              {label:'☕ aufglet 邊佑錫愛店',url:'https://map.naver.com/p/search/aufglet%20한남'},
              {label:'🌿 milestone 咖啡',url:'https://map.naver.com/p/search/마일스톤%20한남'},
            ],
            links:[{cls:'naver',url:'https://map.naver.com/p/search/한남동%20상권',label:'🗺 漢南洞 Naver'}] },
        ]},
        { label:'🥩 晚餐', spots:[
          { id:'kokumi', type:'food', name:'烤黨 KOKUMI 烤肉',
            tags:[{t:'晚餐',c:'food'}],
            why:'米其林推薦！備長炭快烤＋松露炸醬麵現刨松露，視覺味覺雙重震撼',
            links:[{cls:'naver',url:'https://map.naver.com/p/search/화로구이%20성수%20코쿠미',label:'🗺 Naver Map'}] },
        ]},
      ],
      alts:[
        {id:'alt-d3-1',name:'Rue de Rivoli 法式早午餐',tag:'備選早午餐',why:'玫瑰辣炒年糕水管麵超獵奇！空間超好拍，聖水洞打卡推薦',link:'https://map.naver.com/p/search/자연도소금빵%20성수'},
        {id:'alt-d3-2',name:'首爾林公園夜散步',tag:'備選景點',why:'漢江邊大公園，夏夜吹風配便利商店飲料，輕鬆解壓最佳選擇',link:'https://map.naver.com/p/search/서울숲공원'},
        {id:'alt-d3-3',name:'梨泰院解放村美食',tag:'備選晚餐',why:'漢南洞旁邊，異國料理多元，韓劇梨泰院Class場景就在這',link:'https://map.naver.com/p/search/이태원%20해방촌'},
      ],
    },

    D4: {
      emoji: '💆',
      title: 'D4 — 醫美 + 江南掃貨',
      subtitle: '江南醫美療程 → COEX星空圖書館 → 新沙洞林蔭道',
      area: '📍 江南 · 新沙洞 · COEX · 蠶室',
      pikmin: {
        title: 'D4 皮克敏攻略',
        estimate: '🌿 預估花苗 40+（稀有款最多！）',
        tips: [
          {icon:'🏥',text:'診所等待時間正好開 APP 收花苗！江南區醫美診所密集，「醫療」類花苗在這裡'},
          {icon:'📚',text:'COEX 星空圖書館是「圖書館」特殊花苗，全首爾稀有！在裡面慢慢逛多停一下'},
          {icon:'🌳',text:'新沙洞林蔭道走一整條街，「商店」花苗連成一線，邊逛邊收不知不覺就滿了'},
          {icon:'🏙',text:'江南區是首爾最大的商業區，「辦公室」類花苗也會出現，種類最多樣的一天'},
          {icon:'💡',text:'今天花苗數量雖然少一點，但稀有款最多！圖書館花苗記得截圖紀念'},
        ],
      },
      sections:[
        { label:'💆 早上 — 醫美療程（建議出發前 2–3 週預約）', spots:[
          { id:'medical', type:'beauty', name:'江南 / 弘大 醫美推薦', isMedical:true,
            clinics:[
              { name:'🏥 Angelmi Clinic（江南） ⭐ 小紅書高評價',
                desc:'周一到周日都營業，Inmode / ONDA / 童顏針，有中文服務，旅客超友善',
                links:[
                  {cls:'web',url:'https://angelmikorea.com',label:'🌐 官網預約'},
                  {cls:'naver',url:'https://map.naver.com/p/search/엔젤미클리닉%20강남',label:'🗺 Naver Map'},
                ] },
              { name:'🏥 HeyDay Clinic（江南） ⭐ 2026 PTT/Dcard 推薦',
                desc:'自然美學不誇張，多國語言接待，第一次做韓國醫美首選，環境像咖啡廳',
                links:[{cls:'naver',url:'https://map.naver.com/p/search/헤이데이클리닉%20강남',label:'🗺 Naver Map'}] },
              { name:'🏥 Daybeau Clinic（弘大） — 不想跑江南就選這間',
                desc:'弘大附近超方便，翻譯1對1陪同全程，水光針、Inmode 評價很好，週末也開',
                links:[
                  {cls:'web',url:'https://daybeauclinic02.com',label:'🌐 官網預約'},
                  {cls:'naver',url:'https://map.naver.com/p/search/데이뷰클리닉%20홍대',label:'🗺 Naver Map'},
                ] },
            ],
            warn:'2026年起醫美退稅已全面取消！但仍比台灣便宜30–50%。推薦做鈦提升、水光針等恢復期短的療程。' },
        ]},
        { label:'📚 下午 — 江南逛街', spots:[
          { id:'coex', type:'photo', name:'COEX 星空圖書館',
            tags:[{t:'拍照',c:'photo'},{t:'逛街',c:'shop'}],
            why:'2026 首爾最紅打卡點！兩層樓高書牆震撼，拍照出片率爆表',
            desc:'免費入場，逛完直接接 COEX 水族館（🐠）或購物中心。',
            shops:[
              {label:'📚 星空圖書館',url:'https://map.naver.com/p/search/COEX%20별마당도서관'},
              {label:'🐠 COEX 水族館',url:'https://map.naver.com/p/search/코엑스아쿠아리움'},
              {label:'🛍 COEX MALL',url:'https://map.naver.com/p/search/코엑스몰'},
            ],
            links:[{cls:'naver',url:'https://map.naver.com/p/search/COEX%20별마당도서관',label:'🗺 COEX Naver'}] },
          { id:'garosu', type:'shop', name:'新沙洞林蔭道（가로수길）',
            tags:[{t:'購物',c:'shop'},{t:'拍照',c:'photo'}],
            why:'江南最有情調的購物街，梧桐樹成蔭，高端韓牌＋咖啡廳集中地',
            shops:[
              {label:'👓 Gentle Monster 江南',url:'https://map.naver.com/p/search/젠틀몬스터%20가로수길'},
              {label:'🧴 TAMBURINS 林蔭道',url:'https://map.naver.com/p/search/탬버린즈%20가로수길'},
              {label:'☕ 精品咖啡廳群',url:'https://map.naver.com/p/search/가로수길%20카페'},
            ],
            links:[{cls:'naver',url:'https://map.naver.com/p/search/가로수길',label:'🗺 新沙洞 Naver'}] },
        ]},
        { label:'🍖 晚餐', spots:[
          { id:'d4-dinner', type:'food', name:'滿足五香豬腳（米其林必比登）',
            tags:[{t:'晚餐',c:'food'}],
            why:'米其林推薦！五種口味豬腳皮Q肉嫩，配燒酒完美結尾',
            links:[{cls:'naver',url:'https://map.naver.com/p/search/만족오향족발',label:'🗺 Naver Map'}] },
        ]},
      ],
      alts:[
        {id:'alt-d4-1',name:'樂天世界遊樂園',tag:'備選體驗',why:'世界最大室內遊樂園！蠶室站直達，不怕曬超方便',link:'https://map.naver.com/p/search/롯데월드'},
        {id:'alt-d4-2',name:'樂天世界塔 Seoul Sky',tag:'備選景點',why:'全球第三高觀景台，首爾夜景一覽無遺，網美必打卡',link:'https://map.naver.com/p/search/롯데월드타워%20서울스카이'},
        {id:'alt-d4-3',name:'狎鷗亭羅德奧街',tag:'備選逛街',why:'江南頂級購物街，精品旗艦店＋高端美食，整型街也在這',link:'https://map.naver.com/p/search/압구정로데오%20상권'},
      ],
    },

    D5: {
      emoji: '🌸',
      title: 'D5 (7/19) — 明洞掃貨 + 南山夜景',
      subtitle: '明洞全力掃貨 → 南山首爾塔夜景 → 東大門宵夜',
      area: '📍 明洞 · 南山 · 東大門',
      pikmin: {
        title: 'D5 皮克敏攻略',
        estimate: '🌿 預估花苗 55+',
        tips: [
          {icon:'🛍',text:'明洞是首爾花苗密度 Top 1！「商店」花苗幾乎每走 10 步就一個，OLIVE YOUNG 附近特別密'},
          {icon:'🗼',text:'N 首爾塔是「觀光地」稀有花苗，纜車上山途中也會收到「交通」花苗，一次兩個！'},
          {icon:'🌙',text:'東大門深夜還在營業，凌晨繼續收「商店」花苗，首爾特有的深夜購物體驗'},
          {icon:'🏛',text:'DDP 東大門設計廣場是「建築」稀有花苗，外型超特別，拍照打卡順便收'},
          {icon:'💡',text:'今天是倒數第二天，把之前沒收到的花苗補齊！明洞逛的時候慢慢走不要衝'},
        ],
      },
      sections:[
        { label:'💊 早上 — 明洞全力掃貨', spots:[
          { id:'myeongdong-shop', type:'shop', name:'明洞 OLIVE YOUNG 旗艦 + 血拼',
            tags:[{t:'購物',c:'shop'}],
            why:'兩層樓 OLIVE YOUNG 旗艦！明洞換錢匯率全首爾最好，先換錢再買',
            shops:[
              {label:'💊 OLIVE YOUNG 明洞旗艦',url:'https://map.naver.com/p/search/올리브영%20명동%20플래그십'},
              {label:'🌸 3CE 粉紅飯店',url:'https://map.naver.com/p/search/3CE%20명동'},
              {label:'🏬 樂天百貨免稅',url:'https://map.naver.com/p/search/롯데면세점%20명동'},
              {label:'🏬 新世界百貨',url:'https://map.naver.com/p/search/신세계백화점%20명동'},
              {label:'💱 換錢所（匯率最好）',url:'https://map.naver.com/p/search/명동%20환전'},
            ],
            links:[{cls:'naver',url:'https://map.naver.com/p/search/명동%20상권',label:'🗺 明洞商圈 Naver'}] },
          { id:'myeongdong-food', type:'food', name:'明洞小吃街 + ISAAC 三明治',
            tags:[{t:'午餐',c:'food'}],
            why:'路邊攤一條街！糖餅、魚板、辣炒年糕邊逛邊吃，ISAAC 蛋三明治必試',
            links:[{cls:'naver',url:'https://map.naver.com/p/search/명동%20노점%20길거리음식',label:'🗺 明洞夜市街'}] },
        ]},
        { label:'🗼 傍晚 — 南山首爾塔（5–6 點上去最美）', spots:[
          { id:'n-tower', type:'photo', name:'N 首爾塔 + 愛情鎖 💕',
            tags:[{t:'拍照',c:'photo'},{t:'體驗',c:'exp'},{t:'💕 兩人必去',c:'exp'}],
            why:'看夕陽轉夜景，愛情鎖牆留下你們的名字💕 D5 最完美的收尾',
            desc:'傍晚 5–6 點上去，夕陽 + 夜景一次收。南山纜車記得事先買票！',
            links:[
              {cls:'kkday',url:'https://www.kkday.com/zh-tw/product/1261',label:'🎫 KKday 門票'},
              {cls:'klook',url:'https://www.klook.com/zh-TW/activity/396-n-seoul-tower',label:'🎫 Klook 門票'},
              {cls:'naver',url:'https://map.naver.com/p/search/N서울타워',label:'🗺 Naver Map'},
            ] },
        ]},
        { label:'🍗 晚上 — 東大門宵夜', spots:[
          { id:'d5-chicken', type:'food', name:'陳玉華一隻雞',
            tags:[{t:'宵夜',c:'food'}],
            why:'東大門必吃！整隻雞燉湯份量超大，配東大門深夜血拼最爽',
            links:[{cls:'naver',url:'https://map.naver.com/p/search/진옥화%20닭한마리',label:'🗺 Naver Map'}] },
          { id:'ddm-shop', type:'shop', name:'東大門深夜掃貨',
            tags:[{t:'購物',c:'shop'}],
            why:'越夜越熱鬧！24小時不打烊，明天 Check out 前最後補貨機會',
            shops:[
              {label:'🏬 Doota Mall',url:'https://map.naver.com/p/search/두타몰%20동대문'},
              {label:'🏬 Lotte Fitin',url:'https://map.naver.com/p/search/롯데피트인%20동대문'},
              {label:'🏬 Migliore',url:'https://map.naver.com/p/search/밀리오레%20동대문'},
              {label:'🏛 DDP 設計廣場（拍照）',url:'https://map.naver.com/p/search/DDP%20동대문'},
            ],
            links:[{cls:'naver',url:'https://map.naver.com/p/search/동대문%20상권',label:'🗺 東大門 Naver'}] },
        ]},
      ],
      alts:[
        {id:'alt-d5-1',name:'廣藏市場最後一吃',tag:'備選宵夜',why:'明洞旁邊超近，最後一次麻藥飯捲，順手帶食材伴手禮回台灣',link:'https://map.naver.com/p/search/광장시장'},
        {id:'alt-d5-2',name:'南大門市場',tag:'備選逛街',why:'明洞旁傳統批發市場，首飾＋童裝最便宜，伴手禮最後採購',link:'https://map.naver.com/p/search/남대문시장'},
        {id:'alt-d5-3',name:'德壽宮石牆路',tag:'備選景點',why:'韓國最美散步小路，《鬼怪》拍攝地，明洞步行可到',link:'https://map.naver.com/p/search/덕수궁%20돌담길'},
        {id:'alt-d5-4',name:'神仙雪濃湯 明洞店',tag:'備選餐',why:'牛骨慢熬雪白濃湯，宵夜暖胃完美',link:'https://map.naver.com/p/search/신선설농탕%20명동'},
      ],
    },

    D6: {
      emoji: '✈️',
      title: 'D6 (7/20) — Check Out + 弘大最後一逛',
      subtitle: '洗澡整理 → 11:00 Check Out 寄行李 → 弘大逛街 → 取行李 → 機場',
      area: '📍 弘大 · 延南洞（不跑遠，行李在這）',
      timeline: [
        '🛁 早上 — 洗澡、整理行李、打包',
        '🧳 11:00 — Check Out，行李寄放在 Airbnb（同日寄放免費）',
        '🛍 11:00–17:00 — 弘大附近輕鬆逛街、吃午餐',
        '🧳 17:00 — 回 Airbnb 取行李',
        '🚇 18:40 — 出發搭 AREX 普通列車（弘大入口站，約 52 分鐘）',
        '⚠️ 仁川機場 T2！不要搭到 T1！',
        '🛫 19:40 — 抵達仁川機場 T2（起飛前 3 小時）',
        '✈️ 22:40 — 起飛！回台灣 🌸',
      ],
      pikmin: {
        title: 'D6 皮克敏攻略',
        estimate: '🌿 最後衝刺！預估總計 250-300 個',
        tips: [
          {icon:'🏃',text:'今天時間有限！Check Out 前把弘大商圈最後一輪走完，把之前沒收到的補齊'},
          {icon:'🚇',text:'搭 AREX 去機場途中繼續開 APP！「交通」花苗最後再收一波'},
          {icon:'✈️',text:'仁川機場也有花苗！候機時間開著，「機場」特殊花苗難得收到，首爾最後紀念'},
          {icon:'🌿',text:'回到台灣記得截圖這次首爾一共收了多少花苗，給我看！'},
          {icon:'💡',text:'整趟首爾旅行預估總花苗：250-300 個！創個人紀錄吧 🎉'},
        ],
      },
      sections:[
        { label:'🍳 早上 — 最後一次弘大早餐', spots:[
          { id:'d6-breakfast', type:'food', name:'弘大早餐最後一頓',
            tags:[{t:'早餐',c:'food'}],
            why:'最後一頓首爾早餐，隨意選一間走進去就對了',
            shops:[
              {label:'🍳 Egg Drop 弘大',url:'https://map.naver.com/p/search/Egg%20Drop%20홍대'},
              {label:'🥐 附近咖啡廳',url:'https://map.naver.com/p/search/홍대%20카페'},
              {label:'🏪 CU 便利商店（輕食）',url:'https://map.naver.com/p/search/CU%20홍대입구역'},
            ] },
        ]},
        { label:'🛍 11:00 Check Out → 行李寄放 → 繼續逛', spots:[
          { id:'d6-shop', type:'shop', name:'弘大 + 延南洞最後掃貨',
            tags:[{t:'購物',c:'shop'}],
            why:'行李寄在 Airbnb，輕裝出發！弘大最後一輪，缺什麼補什麼',
            shops:[
              {label:'💊 OLIVE YOUNG 弘大',url:'https://map.naver.com/p/search/올리브영%20홍대'},
              {label:'🐱 KAKAO FRIENDS',url:'https://map.naver.com/p/search/카카오프렌즈%20홍대'},
              {label:'📦 DAISO 7層旗艦',url:'https://map.naver.com/p/search/다이소%20홍대'},
              {label:'🏠 Butter 選物',url:'https://map.naver.com/p/search/버터%20홍대'},
              {label:'☕ 延南洞咖啡廳散步',url:'https://map.naver.com/p/search/연남동%20카페'},
            ],
            links:[{cls:'naver',url:'https://map.naver.com/p/search/홍대%20상권',label:'🗺 弘大商圈 Naver'}] },
        ]},
        { label:'🍜 午餐', spots:[
          { id:'d6-lunch', type:'food', name:'弘大最後一餐',
            tags:[{t:'午餐',c:'food'}],
            why:'在弘大吃最後一頓韓國料理，告別首爾！',
            shops:[
              {label:'🍲 百年百歲蔘雞湯',url:'https://map.naver.com/p/search/백년옥%20홍대%20삼계탕'},
              {label:'🥩 小豬存錢筒烤肉',url:'https://map.naver.com/p/search/돼지저금통%20홍대'},
              {label:'🐔 橋村炸雞',url:'https://map.naver.com/p/search/교촌치킨%20홍대'},
            ] },
          { id:'d6-airport', type:'exp', isAirport:true, name:'✈️ 18:40 出發去機場',
            desc:'📍 弘大入口站 搭 AREX 普通列車\n⏱ 約 52 分鐘 → 仁川機場 T2\n⚠️ 注意是 T2 航廈！不要搭到 T1！\n💡 建議先在弘大站買好 AREX 票再出發',
            links:[{cls:'naver',url:'https://map.naver.com/p/search/홍대입구역',label:'🗺 弘大入口站 Naver'}] },
        ]},
      ],
      alts:[],
    },

  },
};
